August/August_27_Find_right_interval.cpp
Please let me know if there are any more changes to be made to the code.
=> Added solution for August_27 - Find right interval

September/Sept_19_Sequential_Digits.cpp
Added Solution for the 19th September Leetcoding Challenge - Sequential Digits
=> Created new file for 19th September Question - Sequential Digits

August/August_23_Stream_of_Characters.cpp
Added August_23_Stream_of_Characters.cpp in August folder as part of the task assigned to me.
Please accept my pull request.
Thanks.
=> Added August 23 Stream of Characters solution

September/Sept_26_Teemo_Attacking.cpp
Solution for September 26 LeetCode Problem.
=> Added Solution for September 26

Move Zeroes.cpp
=>  Move Zeroes.cpp

Group Anagrams.cpp
=> Group Anagrams.cpp

April/Contiguous_Array.cpp, April/Search_in_Rotated_Sorted_Array.cpp
Added the solutions of :
1. Contiguous Array
2. Search in Rotated Sorted Array
=> Added both of my solutions 

April/April_25_Jump_Game.cpp, April/April_26_Longest_Common_Subsequence.cpp, october/Oct_2_Combination_Sum.cpp
Added C++ Solution in a folder titled April
=> April LeetCode Ques Day-25 and 26

April/README.md, April/bitwise-and-of-numbers-range.cpp
In Issue #54 Created April Folder and Added Solution for Day 26 which was assigned by @priyanshisharma ma'am, Updated the README.md for the same
=> Added Solution of Day 23

April/April17_number_of_islands.cpp, April/April24_LRU_cache.cpp
This PR is for the problems assigned to me in issue #54 .
=> created april folder and added april 17 and 24 codes

April_12_Last_Stone_Weight.Java
@priyanshisharma pls review this PR
=> April_12_Last_Stone_Weight.Java

October/Day1_NumberOfRecentCalls.cpp, README.md
Added Day1 solution
Added October Challenge card in Readme
=> Added October challenge Day 1 solution

September/Sept_23_Gas_Station.cpp
Added solution to 23rd September LeetCode challenge.
=> Added Sept_23_Gas_Station.cpp

October/06_Insert_into_BST.cpp, October/07_Rotate_List.cpp
Just for Hactoberfest... 👅 😂 
If you find a better way to solve this, do suggest ✌️ .
=> Added Day 6 & 7 Solution

October/Day_08_Solution.java
=> Create october Day_08_Solution.java

October/Day12_Buddy_Strings.py
It's a bit harder than I thought ngl
Happy Coding ~
=> Added Oct Day 12 solution in Python

October/Day14_house_robber_ii.cpp
problem link - https://leetcode.com/problems/house-robber-ii/
=> Added solution for house robber problem

October/Day5_1009ComplementOfBase10Integer.cpp
Added solution to #1001 Complement of Base 10 Integer
=> Added Day 5 October

April/April_18_Minimum_Path_Sum.cpp
[Minimum Path Sum](https://leetcode.com/explore/challenge/card/30-day-leetcoding-challenge/530/week-3/3303/) solved using dynamic programming
=> Minimum path Sum solved using DP [April - 18]

README.md
Since there are no explore cards anymore
=> docs: remove explore card
